---
title: "NBA Dashboard"
author: "Vlad Tomutiu"
format: dashboard
---

## Dashboard

HOW NBA PLAYER ROLES AND SCORING TRENDS SHAPE OUTPUT

The 2023 NBA season data set used can be found at <https://www.kaggle.com/datasets/amirhosseinmirzaie/nba-players-stats2023-season/code>

The data set has every NBA player from the 2023 season, filtered to include only players that played enough to not create outliers . The data includes player names, positions, age, games played, and statistics like points, rebounds, assists, field goal percentage, and +/-. I made visualizations to answer the questions below:

-   Does NBA players efficiency correlate to scoring output?
-   How is scoring, assisting, and rebounding distributed within the league?
-   Does NBA players +/- (the point differential (points scored minus points allowed) for a team while a specific player is on the court) correlate based on how good of a scorer the player is?
-   Do player positions affect their contribution to specific stats and their overall role on the team?

## Row 1

```{r}
library(tidyverse)
library(plotly)
library(janitor)

nba <- read_csv("data/2023_nba_player_stats.csv")

nba <- nba %>%
  clean_names()

nba_filtered <- nba %>% 
  filter(!(pos %in% c("F", "G"))) %>%
  filter(!(p_name %in% c("Chance Comanche", "Skylar Mays"))) %>%
  filter(fg_percent >= 30, fg_percent <= 70) %>%
  mutate(ppg = pts / gp,
         apg = ast / gp,
         rpg = reb / gp
         )

knitr::kable(nba_filtered)
```
