---
title: "visualizations"
format: dashboard
---

```{r}
library(tidyverse)
library(plotly)
library(janitor)

nba <- read_csv("data/2023_nba_player_stats.csv")

nba <- nba %>%
  clean_names()
```

## Row 1

```{r}
nba_filtered <- nba %>% 
  filter(!(pos %in% c("F", "G"))) %>%
  filter(!(p_name %in% c("Chance Comanche", "Skylar Mays"))) %>%
  filter(fg_percent >= 30, fg_percent <= 70) %>%
  mutate(ppg = pts / gp,
         apg = ast / gp,
         rpg = reb / gp
         )

p <- ggplot(nba_filtered, aes(x = fg_percent, y = ppg,
                                text = paste(
                                "Player: ", p_name, "<br>",
                                "FG%: ", fg_percent, "<br>",
                                "Points/Game: ", round(ppg, 1))
)) +
  geom_point(alpha = 0.6, color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1)) +
  labs(title = "Points Per Game vs. Field Goal Percentage",
       x = "Field Goal %", 
       y = "Points Per Game") +
  theme_light()

ggplotly(p, tooltip = "text")
```

```{r}
nba_filtered <- nba %>% 
  filter(!(pos %in% c("F", "G"))) %>%
  filter(!(p_name %in% c("Chance Comanche", "Skylar Mays"))) %>%
  filter(fg_percent >= 30, fg_percent <= 70) %>%
  mutate(ppg = pts / gp,
         apg = ast / gp,
         rpg = reb / gp
         )

nba_filtered <- nba_filtered %>%
  pivot_longer(cols = c(ppg, apg, rpg),
               names_to = "stat",
               values_to = "value")


ggplot(nba_filtered, aes(x = stat, y = value, fill = stat)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.5) +
  labs(title = "Distribution of PPG, APG, and RPG",
       x = "NBA Metric",
       y = "Per Game Value") +
  theme_classic()
```

```{r}
nba_filtered <- nba %>% 
  filter(!(pos %in% c("F", "G"))) %>%
  filter(!(p_name %in% c("Chance Comanche", "Skylar Mays"))) %>%
  filter(fg_percent >= 30, fg_percent <= 70) %>%
  mutate(ppg = pts / gp,
         apg = ast / gp,
         rpg = reb / gp
         )

p <- ggplot(nba_filtered, aes(x = x/gp, y = pts/gp, 
                       text = paste(
                         "Player: ", p_name, "<br>",
                         "+/- per Game: ", round(x/gp, 2), "<br>",
                         "Points per Game: ", pts/gp
                       ))) +
  geom_point(alpha = 0.7, color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1)) +
  labs(
    title = "Do Players With Higher +/- per Game Score More?",
    x = "+/- per Game",
    y = "Points Per Game"
  ) +
  theme_classic()


plotly::ggplotly(p, tooltip = "text")
```

## Row 2

```{r}
ggplot(nba_filtered, aes(x = pos, y = pts/gp, fill = pos)) +
  geom_boxplot(alpha = 0.7) +
  labs(title = "Points Per Game by Position",
       x = "Position",
       y = "Points Per Game") +
  theme_classic() +
  theme(legend.position = "none")

```

```{r}
ggplot(nba_filtered, aes(x = pos, y = reb/gp, fill = pos)) +
  geom_boxplot(alpha = 0.7) +
  labs(title = "Rebounds Per Game by Position",
       x = "Position",
       y = "Rebounds Per Game") +
  theme_classic() +
  theme(legend.position = "none")
```

```{r}
ggplot(nba_filtered, aes(x = pos, y = ast/gp, fill = pos)) +
  geom_boxplot(alpha = 0.7) +
  labs(title = "Assists Per Game by Position",
       x = "Position",
       y = "Assists Per Game") +
  theme_classic() +
  theme(legend.position = "none")
```

```{r}
ggplot(nba_filtered, aes(x = pos, y = pts/gp+ast/gp+reb/gp, fill = pos)) +
  geom_boxplot(alpha = 0.7) +
  labs(title = "PPG+APG+RPG Per Game by Position",
       x = "Position",
       y = "PPG+APG+RPG") +
  theme_classic() +
  theme(legend.position = "none")
```
